CREATE TABLE IF NOT EXISTS `agentx_user_entitlement` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT NOT NULL DEFAULT 0,
    `user_id` BIGINT NOT NULL,
    `agent_id` VARCHAR(64) DEFAULT NULL COMMENT 'Agent ID，NULL 表示全局权限',
    `dept_name` VARCHAR(100) DEFAULT NULL,
    `job_title` VARCHAR(100) DEFAULT NULL,
    `role_tags` JSON DEFAULT NULL,
    `work_region` VARCHAR(50) DEFAULT NULL,
    `allowed_actions` JSON NOT NULL,
    `resource_filters` JSON DEFAULT NULL,
    `obligations` JSON DEFAULT NULL,
    `policy_version` VARCHAR(50) DEFAULT NULL,
    `effective_from` DATETIME DEFAULT NULL,
    `effective_until` DATETIME DEFAULT NULL,
    `creator` VARCHAR(64) DEFAULT '',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` VARCHAR(64) DEFAULT '',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` BIT(1) NOT NULL DEFAULT b'0',
    PRIMARY KEY (`id`),
    KEY `idx_tenant_user_agent` (`tenant_id`, `user_id`, `agent_id`),
    KEY `idx_policy_version` (`tenant_id`, `policy_version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AgentX 用户权限配置';

CREATE TABLE IF NOT EXISTS `agentx_access_audit` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT NOT NULL DEFAULT 0,
    `decision_id` VARCHAR(64) NOT NULL,
    `user_id` BIGINT NOT NULL,
    `channel_user_id` VARCHAR(255) NOT NULL,
    `agent_id` VARCHAR(64) NOT NULL,
    `conversation_scope` VARCHAR(255) DEFAULT NULL,
    `action` VARCHAR(100) DEFAULT NULL,
    `resource_type` VARCHAR(50) DEFAULT NULL,
    `resource_id` VARCHAR(255) DEFAULT NULL,
    `decision` VARCHAR(20) NOT NULL COMMENT 'ALLOW/DENY/REQUIRE_BINDING',
    `deny_reason` VARCHAR(255) DEFAULT NULL,
    `policy_version` VARCHAR(50) DEFAULT NULL,
    `request_time` DATETIME NOT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_tenant_decision_id` (`tenant_id`, `decision_id`),
    KEY `idx_tenant_user_time` (`tenant_id`, `user_id`, `request_time`),
    KEY `idx_tenant_agent_time` (`tenant_id`, `agent_id`, `request_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AgentX 访问决策审计日志';
