SET NAMES utf8mb4;

ALTER TABLE `erp_account`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_customer`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_finance_payment`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_finance_payment_item`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_finance_receipt`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_finance_receipt_item`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_product`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_product_category`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_product_unit`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_purchase_in`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_purchase_in_items`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_purchase_order`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_purchase_order_items`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_purchase_return`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_purchase_return_items`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_sale_order`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_sale_order_items`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_sale_out`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_sale_out_items`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_sale_return`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_sale_return_items`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_stock`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_stock_check`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_stock_check_item`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_stock_in`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_stock_in_item`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_stock_move`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_stock_move_item`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_stock_out`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_stock_out_item`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_stock_record`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_supplier`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

ALTER TABLE `erp_warehouse`
  ADD COLUMN IF NOT EXISTS `creator` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updater` varchar(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `deleted` bit(1) NOT NULL DEFAULT b'0';

