CREATE TABLE IF NOT EXISTS `agentx_audit_event` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `tenant_id` BIGINT NOT NULL DEFAULT 0,
    `initiator_id` VARCHAR(64) DEFAULT NULL,
    `agent_code` VARCHAR(64) DEFAULT NULL,
    `event_type` VARCHAR(64) NOT NULL,
    `scenario_code` VARCHAR(64) DEFAULT NULL,
    `business_key` VARCHAR(128) DEFAULT NULL,
    `openfang_task_run_id` VARCHAR(128) DEFAULT NULL,
    `openfang_approval_id` VARCHAR(128) DEFAULT NULL,
    `tool_name` VARCHAR(64) DEFAULT NULL,
    `risk_level` INT DEFAULT NULL,
    `data_scope_summary` VARCHAR(1024) DEFAULT NULL,
    `request_summary` VARCHAR(1024) DEFAULT NULL,
    `duration_ms` BIGINT DEFAULT NULL,
    `error_code` INT DEFAULT NULL,
    `business_impact_summary` VARCHAR(1024) DEFAULT NULL,
    `result_summary` VARCHAR(1024) DEFAULT NULL,
    `creator` VARCHAR(64) DEFAULT '',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` VARCHAR(64) DEFAULT '',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` BIT(1) NOT NULL DEFAULT b'0',
    PRIMARY KEY (`id`),
    KEY `idx_tenant_event_create` (`tenant_id`, `event_type`, `create_time`),
    KEY `idx_task_run` (`openfang_task_run_id`),
    KEY `idx_business_key` (`business_key`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = 'AgentX 审计事件';
